title: COVID 19 forecast hub
baseurl: ''
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: Your source for up-to-date forecasts of COVID-19.
palette: navy
palettes:
  blue:
    sass:
      accent1: '#00c6ff'
      accent2: '#0072ff'
  green:
    sass:
      accent1: '#12db5d'
      accent2: '#11998e'
  navy:
    sass:
      accent1: '#004e92'
      accent2: '#000428'
  violet:
    sass:
      accent1: '#8e2de2'
      accent2: '#4a00e0'
header:
  title: COVID 19 forecast hub
  logo_img: images/forecast-hub-logo_DARKBLUE.png
  has_nav: true
  nav_links:
    - label: Home
      url: /
      type: link
      has_subnav: false
#    - label: Team
#      url: /team/
#      type: link
#      has_subnav: false
    - label: Visualization
      url: 'https://viz.covid19forecasthub.org/'
      type: link
      has_subnav: false
      new_window: true
    - label: Reports
      url: /doc/reports/
      type: link
      has_subnav: false
    - label: Data
      url: /data/
      type: link
      has_subnav: false
    - label: Community
      url: '/community/'
      type: link
      has_subnav: false
    - label: About
      url: /doc/
      type: link
      has_subnav: false
    - label: GitHub
      url: 'https://github.com/reichlab/covid19-forecast-hub'
      type: primary
      has_subnav: false
      new_window: true
footer:
  content: 'Forecast data are available by default under a <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank">CC BY 4.0 license</a>. Some models have specific licenses. See <a href="https://github.com/reichlab/covid19-forecast-hub/blob/master/README.md#the-covid-forecast-hub-team" target="_blank">repository</a> for details. <br> The COVID-19 Forecast Hub has been supported by the US Centers for Disease Control and Prevention (U01IP001122-01-05) and the US National Institutes of Health (R35GM119582). Contributing teams may have received additional funding to support their contributions. The content of the COVID-19 Forecast Hub is solely the responsibility of the participating teams and the Hub maintainers and does not necessarily represent the official views of NIH, CDC, or other funders.'
#  links:
#    - label: CC BY 4.0
#      url: 'https://creativecommons.org/licenses/by/4.0/'
#      type: link
#      new_window: true
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/reichlab'
      type: icon
      icon_class: fa-twitter
      new_window: true
    - label: GitHub
      url: 'https://github.com/reichlab/covid19-forecast-hub'
      type: icon
      icon_class: fa-github
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - ssg-build.sh
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
  - deploy.sh
  - update-community.py
  - README.theme.md
  - stackbit.yaml
  - requirements.txt
  - update-reports.py
  - Pipfile
  - Pipfile.lock
  - archive/
